[build]
  publish = "storybook-static"
  command = "yarn build-storybook"
  # No deployment is done here, so it's not really relevant.
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/*"